.\" The cournol man page. 
.\" Contact fabian.foerg@gmx.de to correct errors or omissions. 
.TH COURNOL 1 "2007-05-31" "GNU" "cournol manual"
.SH NAME
cournol \- a program for analyzing absolute supply monopolies and polypolies
.SH DESCRIPTION
Cournol is a GTK+ based application for analyzing absolute supply monopolies and polypolies.
The program calculates the most important information of such market types
(e. g. maximum profit) and draws the respective graphs.
.SH OPTIONS
Cournol does not use any specific command line options. Nevertheless, the standard
GTK+ command line options can be used. See "man gtk-options".
.SH BUGS
Report bugs to <fabian.foerg@gmx.de>.
.SH AUTHOR
Fabian Foerg <fabian.foerg@gmx.de> (http://cournol.k-2007.de/)
.SH COPYRIGHT
.P
Copyright \(co 2007 Fabian Foerg.
.P
This  is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
